version: 2

sources:
  - name: jaffle_shop
    description: 'A sample database for raw data in postgres'
    database: raw  
    schema: jaffle_shop  
    tables:
      - name: orders
      - name: customers

  - name: stripe
    tables:
      - name: payments
